name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Haiii it seems like this is your first issue congratulations *★,°*:.☆(￣▽￣)/$:*.°★* 。'
        pr-message: 'Haiii it seems like this is your first pull request congratulations (ﾉ◕ヮ◕)ﾉ*:･ﾟ✧'
